### ISSUE TITLE
MUIs broken on High Sierra with recent Haskell Platform versions

### ISSUE THREAD

**Issue by donya** [Euterpea/HSoM#7]
An update to something in HSoM's chain of dependencies now yields this when trying to run any MUI.

GLUT Fatal Error: internal error: NSInternalInconsistencyException, reason: nextEventMatchingMask should only be called from the Main Thread!

This happens from both ghci (which has always been buggy with MUIs) and also compiled executables. I am currently looking into solutions.

**Comment by donya** [comment]
This is due to using -rtsopts and/or -threaded in compiling programs. This appears to now be a fairly wide-spread issue with anything using GLUT on Mac (not just with Haskell) so it is unlikely to have a good solution. This means that MUIs can't be used in threaded contexts, which may limit performance in more demanding situations. 

How to avoid the error:

- Do not compile programs using MUIs using -rtsopts or -threaded
- Avoid using fork etc. to spawn threads.

Windows is not affected by these issues and threaded applications with MUIs will behave correctly.

**Comment by seanmcl** [comment]
I just hit this with the latest Euterpea, HSoM and High Sierra.  I see it's closed.  What is the workaround?  I don't see "rtsopts" or "threaded" in either repo.  I see `forkIO` in MidiIO.lhs.  Should we try to rewrite the functions that use it?

Thanks.

**Comment by seanmcl** [comment]
Sorry, I see there are comments here: http://www.euterpea.com/download-and-installation/
